### ISSUE TITLE
Clone và chạy lại project 

### ISSUE THREAD

**Issue by anhTuspham** [anhTuspham/video-editing-group10#1]
- [x] #4
- [x] #5
- [x] Chạy chương trình ở file client

**Comment by ThuatVDQ** [comment]
Lỗi khi chạy server: thiếu connection string của mongodb

**Comment by ThuatVDQ** [comment]
[clone and run.docx](https://github.com/anhTuspham/video-editing-group10/files/11009273/clone.and.run.docx)
