### ISSUE TITLE
Tìm hiểu về 1 tool testing để test hệ thống

### ISSUE THREAD

**Issue by anhTuspham** [anhTuspham/video-editing-group10#12]

**Comment by HaoQuangv** [comment]
Task 1: Tìm hiểu về selenium 
[Task1Tuan03.docx](https://github.com/anhTuspham/video-editing-group10/files/11144437/Task1Tuan03.docx)

**Comment by HaoQuangv** [comment]
Task 2: Selenium WebDriver cơ bản
[Task2Tuan03.docx](https://github.com/anhTuspham/video-editing-group10/files/11144518/Task2Tuan03.docx)

**Comment by HaoQuangv** [comment]
Task 3: TestNG
[Task3Tuan03.docx](https://github.com/anhTuspham/video-editing-group10/files/11144704/Task3Tuan03.docx)

**Comment by HaoQuangv** [comment]
Task 4: Frameworks
[Task4Tuan03.docx](https://github.com/anhTuspham/video-editing-group10/files/11144944/Task4Tuan03.docx)

**Comment by HaoQuangv** [comment]
Task 5: Advance Webdriver Stuff!

[Task5Tuan03.docx](https://github.com/anhTuspham/video-editing-group10/files/11145008/Task5Tuan03.docx)

**Comment by HaoQuangv** [comment]
Task 6: Selenium IDE
[Task6Tuan03.docx](https://github.com/anhTuspham/video-editing-group10/files/11145046/Task6Tuan03.docx)

**Comment by HaoQuangv** [comment]
Task 7: 10 BEST Selenium Alternatives

[Task7Tuan03docx.docx](https://github.com/anhTuspham/video-editing-group10/files/11145098/Task7Tuan03docx.docx)
