### ISSUE TITLE
Dựa vào chức năng vẽ usecase diagram

### ISSUE THREAD

**Issue by anhTuspham** [anhTuspham/video-editing-group10#7]
- [x] Đọc code, nghiên cứu các chức năng trang web
- [x] Tìm hiểu về usecase diagram
- [x] Vẽ usecase diagram

**Comment by ThuatVDQ** [comment]
7 ngày tuần 2:
[final-project-week2.docx](https://github.com/anhTuspham/video-editing-group10/files/11087308/final-project-week2.docx)
